import JSZip from "jszip";
import { saveAs } from "file-saver"; // Need to install file-saver too

export const generatePortfolioZip = async (data: any) => {
  const zip = new JSZip();

  // Create Site Structure
  const root = zip.folder("my-portfolio");
  if (!root) return;

  // 1. Generate HTML (Simple but premium template)
  const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${data.name} | Portfolio</title>
    <link rel="stylesheet" href="style.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <div class="logo">${data.name.charAt(0)}<span>.</span></div>
    </header>
    <main>
        <section class="hero">
            <h1>Hi, I'm <span>${data.name}</span></h1>
            <h2>${data.role}</h2>
            <p>${data.bio}</p>
        </section>
        <section id="projects">
            <h3>Projects</h3>
            <div class="grid">
              ${data.projects?.map((p: any) => `
                <div class="card">
                    <h4>${p.title}</h4>
                    <p>${p.desc}</p>
                </div>
              `).join('')}
            </div>
        </section>
    </main>
    <footer>
        <p>© 2026 ${data.name} | Generated by PortGen</p>
    </footer>
</body>
</html>
  `;

  // 2. Generate CSS
  const cssContent = `
:root {
    --bg: #030305;
    --text: #fff;
    --accent: #3b82f6;
}
body { background: var(--bg); color: var(--text); font-family: 'Inter', sans-serif; margin: 0; }
.container { max-width: 1100px; margin: 0 auto; padding: 0 2rem; }
span { color: var(--accent); }
.hero { padding: 8rem 2rem; text-align: center; }
.grid { display: grid; grid-template-columns: 1fr 1fr; gap: 2rem; }
.card { background: rgba(255,255,255,0.05); padding: 2rem; border-radius: 1rem; border: 1px solid rgba(255,255,255,0.1); }
  `;

  root.file("index.html", htmlContent);
  root.file("style.css", cssContent);
  root.file("README.md", `# ${data.name}'s Portfolio\nGenerated with PortGen.\n\n## How to run\nSimply open index.html in your browser.`);

  const content = await zip.generateAsync({ type: "blob" });
  return content;
};
